[phases.setup]
nixPkgs = ["nodejs_18", "pnpm"]

[phases.install]
cmds = ["cd /app && pnpm install --no-frozen-lockfile"]

[phases.build]
cmds = ["cd /app && pnpm build"]

[start]
cmd = "cd /app/apps/backend && pnpm start"
